main: xyz.developmentcl.App
name: BlankTestPlugin
version: 0.1
commands:
  xpshop:
    description: You can buy items with xp!
    usage: /xpshop <item>
  login:
    description: You can login for custom plugins
    usage: /login <password> <password>
  register:
    description: You can register for custom plugins
    usage: /register <password> <password>
  faction:
    description: You can register for custom plugins
    usage: /faction <action> <faction_name>(optional)