version: "3.9"

services:
  db:
    volumes:
      - ./data/db:/var/lib/postgresql/data
    image: postgres
    container_name: postgres_minecraft_server_db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWD}
    ports:
      - 5432:5432
